#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
from pathlib import Path

from benchmark_history import DEFAULT_HISTORY_PATH, append_rows


BACKFILL_ROWS = [
    {
        "backfill_id": "chat_001",
        "backfill_order": 1,
        "script_name": "chat_backfill",
        "record_type": "historical",
        "history_source": "chat_log",
        "experiment_tag": "chat_backfill",
        "backend": "mlx",
        "target_model": "mlx-community/Qwen3.5-4B-MLX-bf16",
        "draft_model": "",
        "prompt_file": "prompts/functional_equation.txt",
        "max_new_tokens": 2048,
        "prompt_tps": 161.75,
        "generation_tps": 39.66,
        "peak_memory_gb": 8.59,
        "notes": "Initial plain MLX BF16 baseline from chat.",
    },
    {
        "backfill_id": "chat_002",
        "backfill_order": 2,
        "script_name": "chat_backfill",
        "record_type": "historical",
        "history_source": "chat_log",
        "experiment_tag": "chat_backfill",
        "backend": "mlx",
        "target_model": "mlx-community/Qwen3.5-4B-MLX-4bit",
        "draft_model": "",
        "prompt_file": "prompts/functional_equation.txt",
        "max_new_tokens": 2048,
        "prompt_tps": 691.09,
        "generation_tps": 115.92,
        "peak_memory_gb": 2.68,
        "notes": "Initial plain MLX 4-bit baseline from chat.",
    },
    {
        "backfill_id": "chat_003",
        "backfill_order": 3,
        "script_name": "chat_backfill",
        "record_type": "historical",
        "history_source": "chat_log",
        "experiment_tag": "chat_backfill",
        "backend": "mps",
        "target_model": "Qwen/Qwen3.5-4B",
        "draft_model": "z-lab/Qwen3.5-4B-DFlash",
        "max_new_tokens": 32,
        "generation_tps": 4.85,
        "avg_acceptance_length": 1.0,
        "notes": "First rough MPS DFlash prototype; draft effectively not helping.",
    },
    {
        "backfill_id": "chat_004",
        "backfill_order": 4,
        "script_name": "chat_backfill",
        "record_type": "historical",
        "history_source": "chat_log",
        "experiment_tag": "chat_backfill",
        "backend": "mps",
        "target_model": "Qwen/Qwen3.5-4B",
        "draft_model": "z-lab/Qwen3.5-4B-DFlash",
        "verify_mode": "full",
        "max_new_tokens": 32,
        "generation_tps": 10.92,
        "avg_acceptance_length": 7.60,
        "notes": "Correct full-verifier MPS v1.",
    },
    {
        "backfill_id": "chat_005",
        "backfill_order": 5,
        "script_name": "chat_backfill",
        "record_type": "historical",
        "history_source": "chat_log",
        "experiment_tag": "chat_backfill",
        "backend": "mps",
        "target_model": "Qwen/Qwen3.5-4B",
        "draft_model": "",
        "max_new_tokens": 32,
        "generation_tps": 7.67,
        "notes": "Plain autoregressive PyTorch/MPS baseline mentioned in chat.",
    },
    {
        "backfill_id": "chat_006",
        "backfill_order": 6,
        "script_name": "chat_backfill",
        "record_type": "historical",
        "history_source": "chat_log",
        "experiment_tag": "chat_backfill",
        "backend": "mps",
        "target_model": "Qwen/Qwen3.5-4B",
        "draft_model": "z-lab/Qwen3.5-4B-DFlash",
        "verify_mode": "cached",
        "max_new_tokens": 32,
        "generation_tps": 9.22,
        "avg_acceptance_length": 7.60,
        "notes": "Cached verifier after Qwen3.5 cache fix on 32-token run.",
    },
    {
        "backfill_id": "chat_007",
        "backfill_order": 7,
        "script_name": "chat_backfill",
        "record_type": "historical",
        "history_source": "chat_log",
        "experiment_tag": "chat_backfill",
        "backend": "mps",
        "target_model": "Qwen/Qwen3.5-4B",
        "draft_model": "z-lab/Qwen3.5-4B-DFlash",
        "verify_mode": "cached",
        "max_new_tokens": 128,
        "generation_tps": 16.98,
        "end_to_end_tps": 14.69,
        "avg_acceptance_length": 9.36,
        "notes": "Cached verifier after Qwen3.5 cache fix on 128-token run.",
    },
    {
        "backfill_id": "chat_008",
        "backfill_order": 8,
        "script_name": "chat_backfill",
        "record_type": "historical",
        "history_source": "chat_log",
        "experiment_tag": "chat_backfill",
        "backend": "mps",
        "target_model": "Qwen/Qwen3.5-4B",
        "draft_model": "z-lab/Qwen3.5-4B-DFlash",
        "verify_mode": "full",
        "max_new_tokens": 128,
        "generation_tps": 18.18,
        "end_to_end_tps": 13.56,
        "avg_acceptance_length": 9.36,
        "notes": "Full verifier comparison on 128-token run.",
    },
    {
        "backfill_id": "chat_009",
        "backfill_order": 9,
        "script_name": "chat_backfill",
        "record_type": "historical",
        "history_source": "chat_log",
        "experiment_tag": "chat_backfill",
        "backend": "mlx",
        "target_model": "mlx-community/Qwen3.5-4B-MLX-bf16",
        "draft_model": "",
        "prompt_file": "prompts/functional_equation.txt",
        "max_new_tokens": 128,
        "generation_tps": 40.43,
        "end_to_end_tps": 24.24,
        "notes": "Cold plain MLX BF16 baseline from first MLX DFlash comparison.",
    },
    {
        "backfill_id": "chat_010",
        "backfill_order": 10,
        "script_name": "chat_backfill",
        "record_type": "historical",
        "history_source": "chat_log",
        "experiment_tag": "chat_backfill",
        "backend": "mlx",
        "target_model": "mlx-community/Qwen3.5-4B-MLX-4bit",
        "draft_model": "",
        "prompt_file": "prompts/functional_equation.txt",
        "max_new_tokens": 128,
        "generation_tps": 116.29,
        "end_to_end_tps": 61.43,
        "notes": "Cold plain MLX 4-bit baseline from first MLX DFlash comparison.",
    },
    {
        "backfill_id": "chat_011",
        "backfill_order": 11,
        "script_name": "chat_backfill",
        "record_type": "historical",
        "history_source": "chat_log",
        "experiment_tag": "chat_backfill",
        "backend": "mlx",
        "target_model": "mlx-community/Qwen3.5-4B-MLX-bf16",
        "draft_model": "z-lab/Qwen3.5-4B-DFlash",
        "prompt_file": "prompts/functional_equation.txt",
        "max_new_tokens": 128,
        "warmup_runs": 1,
        "generation_tps": 49.10,
        "end_to_end_tps": 45.30,
        "avg_acceptance_length": 8.38,
        "notes": "First exact MLX DFlash BF16 prototype.",
    },
    {
        "backfill_id": "chat_012",
        "backfill_order": 12,
        "script_name": "chat_backfill",
        "record_type": "historical",
        "history_source": "chat_log",
        "experiment_tag": "chat_backfill",
        "backend": "mlx",
        "target_model": "mlx-community/Qwen3.5-4B-MLX-4bit",
        "draft_model": "z-lab/Qwen3.5-4B-DFlash",
        "prompt_file": "prompts/functional_equation.txt",
        "max_new_tokens": 128,
        "warmup_runs": 1,
        "generation_tps": 47.68,
        "end_to_end_tps": 44.36,
        "avg_acceptance_length": 7.11,
        "notes": "First exact MLX DFlash with 4-bit target.",
    },
    {
        "backfill_id": "chat_013",
        "backfill_order": 13,
        "script_name": "chat_backfill",
        "record_type": "historical",
        "history_source": "chat_log",
        "experiment_tag": "chat_backfill",
        "backend": "mlx",
        "target_model": "mlx-community/Qwen3.5-4B-MLX-bf16",
        "draft_model": "",
        "prompt_file": "prompts/functional_equation.txt",
        "max_new_tokens": 128,
        "generation_tps": 41.10,
        "end_to_end_tps": 37.92,
        "prompt_tps": 720.23,
        "notes": "Warm same-process plain MLX BF16 baseline.",
    },
    {
        "backfill_id": "chat_014",
        "backfill_order": 14,
        "script_name": "chat_backfill",
        "record_type": "historical",
        "history_source": "chat_log",
        "experiment_tag": "chat_backfill",
        "backend": "mlx",
        "target_model": "mlx-community/Qwen3.5-4B-MLX-4bit",
        "draft_model": "",
        "prompt_file": "prompts/functional_equation.txt",
        "max_new_tokens": 128,
        "generation_tps": 121.10,
        "end_to_end_tps": 99.88,
        "notes": "Warm same-process plain MLX 4-bit baseline.",
    },
    {
        "backfill_id": "chat_015",
        "backfill_order": 15,
        "script_name": "chat_backfill",
        "record_type": "historical",
        "history_source": "chat_log",
        "experiment_tag": "chat_backfill",
        "backend": "mlx",
        "target_model": "mlx-community/Qwen3.5-4B-MLX-bf16",
        "draft_model": "",
        "prompt_file": "prompts/functional_equation.txt",
        "max_new_tokens": 128,
        "generation_tps": 40.67,
        "end_to_end_tps": 37.65,
        "notes": "Warm plain MLX BF16 baseline used for verifier optimization comparison.",
    },
    {
        "backfill_id": "chat_016",
        "backfill_order": 16,
        "script_name": "chat_backfill",
        "record_type": "historical",
        "history_source": "chat_log",
        "experiment_tag": "chat_backfill",
        "backend": "mlx",
        "target_model": "mlx-community/Qwen3.5-4B-MLX-4bit",
        "draft_model": "",
        "prompt_file": "prompts/functional_equation.txt",
        "max_new_tokens": 128,
        "generation_tps": 119.59,
        "end_to_end_tps": 99.00,
        "notes": "Warm plain MLX 4-bit baseline used for verifier optimization comparison.",
    },
    {
        "backfill_id": "chat_017",
        "backfill_order": 17,
        "script_name": "chat_backfill",
        "record_type": "historical",
        "history_source": "chat_log",
        "experiment_tag": "chat_backfill",
        "backend": "mlx",
        "target_model": "mlx-community/Qwen3.5-4B-MLX-bf16",
        "draft_model": "z-lab/Qwen3.5-4B-DFlash",
        "prompt_file": "prompts/functional_equation.txt",
        "max_new_tokens": 128,
        "warmup_runs": 1,
        "generation_tps": 72.01,
        "end_to_end_tps": 67.71,
        "avg_acceptance_length": 8.38,
        "notes": "Best full-block verify plus cache-only replay path before batched rollback.",
    },
    {
        "backfill_id": "chat_018",
        "backfill_order": 18,
        "script_name": "chat_backfill",
        "record_type": "historical",
        "history_source": "chat_log",
        "experiment_tag": "chat_backfill",
        "backend": "mlx",
        "target_model": "mlx-community/Qwen3.5-4B-MLX-4bit",
        "draft_model": "z-lab/Qwen3.5-4B-DFlash",
        "prompt_file": "prompts/functional_equation.txt",
        "max_new_tokens": 128,
        "warmup_runs": 1,
        "generation_tps": 95.73,
        "end_to_end_tps": 87.93,
        "avg_acceptance_length": 7.11,
        "notes": "Best full-block verify plus cache-only replay path before batched rollback with 4-bit target.",
    },
    {
        "backfill_id": "chat_019",
        "backfill_order": 19,
        "script_name": "chat_backfill",
        "record_type": "historical",
        "history_source": "chat_log",
        "experiment_tag": "chat_backfill",
        "backend": "mlx",
        "target_model": "mlx-community/Qwen3.5-4B-MLX-bf16",
        "draft_model": "",
        "prompt_file": "prompts/functional_equation.txt",
        "max_new_tokens": 128,
        "generation_tps": 40.70,
        "end_to_end_tps": 37.03,
        "notes": "Warm plain MLX BF16 baseline before batched rollback.",
    },
    {
        "backfill_id": "chat_020",
        "backfill_order": 20,
        "script_name": "chat_backfill",
        "record_type": "historical",
        "history_source": "chat_log",
        "experiment_tag": "chat_backfill",
        "backend": "mlx",
        "target_model": "mlx-community/Qwen3.5-4B-MLX-4bit",
        "draft_model": "",
        "prompt_file": "prompts/functional_equation.txt",
        "max_new_tokens": 128,
        "generation_tps": 120.21,
        "end_to_end_tps": 97.17,
        "notes": "Warm plain MLX 4-bit baseline before batched rollback.",
    },
    {
        "backfill_id": "chat_021",
        "backfill_order": 21,
        "script_name": "chat_backfill",
        "record_type": "historical",
        "history_source": "chat_log",
        "experiment_tag": "chat_backfill",
        "backend": "mlx",
        "target_model": "mlx-community/Qwen3.5-4B-MLX-bf16",
        "draft_model": "z-lab/Qwen3.5-4B-DFlash",
        "prompt_file": "prompts/functional_equation.txt",
        "max_new_tokens": 128,
        "generation_tps": 101.05,
        "end_to_end_tps": 92.73,
        "avg_acceptance_length": 7.44,
        "notes": "Batched rollback MLX DFlash BF16 milestone.",
    },
    {
        "backfill_id": "chat_022",
        "backfill_order": 22,
        "script_name": "chat_backfill",
        "record_type": "historical",
        "history_source": "chat_log",
        "experiment_tag": "chat_backfill",
        "backend": "mlx",
        "target_model": "mlx-community/Qwen3.5-4B-MLX-4bit",
        "draft_model": "z-lab/Qwen3.5-4B-DFlash",
        "prompt_file": "prompts/functional_equation.txt",
        "max_new_tokens": 128,
        "generation_tps": 163.97,
        "end_to_end_tps": 142.42,
        "avg_acceptance_length": 8.53,
        "notes": "Batched rollback MLX DFlash 4-bit milestone.",
    },
    {
        "backfill_id": "chat_023",
        "backfill_order": 23,
        "script_name": "chat_backfill",
        "record_type": "historical",
        "history_source": "chat_log",
        "experiment_tag": "chat_backfill",
        "backend": "mlx",
        "target_model": "mlx-community/Qwen3.5-4B-MLX-bf16",
        "draft_model": "z-lab/Qwen3.5-4B-DFlash",
        "prompt_file": "prompts/functional_equation.txt",
        "max_new_tokens": 128,
        "generation_tps": 100.45,
        "end_to_end_tps": 92.24,
        "avg_acceptance_length": 7.44,
        "notes": "Tuned verifier options BF16 checkpoint.",
    },
    {
        "backfill_id": "chat_024",
        "backfill_order": 24,
        "script_name": "chat_backfill",
        "record_type": "historical",
        "history_source": "chat_log",
        "experiment_tag": "chat_backfill",
        "backend": "mlx",
        "target_model": "mlx-community/Qwen3.5-4B-MLX-4bit",
        "draft_model": "z-lab/Qwen3.5-4B-DFlash",
        "prompt_file": "prompts/functional_equation.txt",
        "max_new_tokens": 128,
        "generation_tps": 161.15,
        "end_to_end_tps": 140.20,
        "avg_acceptance_length": 8.53,
        "notes": "Tuned verifier options 4-bit checkpoint.",
    },
    {
        "backfill_id": "chat_025",
        "backfill_order": 25,
        "script_name": "chat_backfill",
        "record_type": "historical",
        "history_source": "chat_log",
        "experiment_tag": "chat_backfill",
        "backend": "mlx",
        "target_model": "mlx-community/Qwen3.5-4B-MLX-bf16",
        "draft_model": "z-lab/Qwen3.5-4B-DFlash",
        "prompt_file": "prompts/functional_equation.txt",
        "max_new_tokens": 128,
        "generation_tps": 100.78,
        "end_to_end_tps": 92.54,
        "avg_acceptance_length": 7.44,
        "notes": "Mean of three BF16 stability reruns.",
    },
    {
        "backfill_id": "chat_026",
        "backfill_order": 26,
        "script_name": "chat_backfill",
        "record_type": "historical",
        "history_source": "chat_log",
        "experiment_tag": "chat_backfill",
        "backend": "mlx",
        "target_model": "mlx-community/Qwen3.5-4B-MLX-4bit",
        "draft_model": "z-lab/Qwen3.5-4B-DFlash",
        "prompt_file": "prompts/functional_equation.txt",
        "max_new_tokens": 128,
        "generation_tps": 161.75,
        "end_to_end_tps": 140.68,
        "avg_acceptance_length": 8.53,
        "notes": "Mean of three 4-bit stability reruns.",
    },
    {
        "backfill_id": "chat_027",
        "backfill_order": 27,
        "script_name": "chat_backfill",
        "record_type": "historical",
        "history_source": "chat_log",
        "experiment_tag": "chat_backfill",
        "backend": "mlx",
        "target_model": "mlx-community/Qwen3.5-4B-MLX-bf16",
        "draft_model": "z-lab/Qwen3.5-4B-DFlash",
        "prompt_file": "prompts/functional_equation.txt",
        "max_new_tokens": 128,
        "generation_tps": 101.18137156093248,
        "end_to_end_tps": 87.97629265989953,
        "avg_acceptance_length": 7.444444444444445,
        "exact_match": "true",
        "notes": "Zero-copy exactness check versus plain MLX BF16.",
    },
    {
        "backfill_id": "chat_028",
        "backfill_order": 28,
        "script_name": "chat_backfill",
        "record_type": "historical",
        "history_source": "chat_log",
        "experiment_tag": "chat_backfill",
        "backend": "mlx",
        "target_model": "mlx-community/Qwen3.5-4B-MLX-bf16",
        "draft_model": "z-lab/Qwen3.5-4B-DFlash",
        "prompt_file": "prompts/functional_equation.txt",
        "max_new_tokens": 128,
        "prompt_tps": 895.97,
        "generation_tps": 100.47,
        "end_to_end_tps": 92.30,
        "avg_acceptance_length": 7.44,
        "peak_memory_gb": 9.72,
        "acceptance_lengths": [1, 2, 13, 4, 6, 14, 4, 13, 6, 5, 6, 12, 3, 16, 6, 1, 9, 13],
        "notes": "Zero-copy warm CLI BF16 run.",
    },
    {
        "backfill_id": "chat_029",
        "backfill_order": 29,
        "script_name": "chat_backfill",
        "record_type": "historical",
        "history_source": "chat_log",
        "experiment_tag": "chat_backfill",
        "backend": "mlx",
        "target_model": "mlx-community/Qwen3.5-4B-MLX-4bit",
        "draft_model": "z-lab/Qwen3.5-4B-DFlash",
        "prompt_file": "prompts/functional_equation.txt",
        "max_new_tokens": 128,
        "generation_tps": 161.25894515847727,
        "end_to_end_tps": 132.43649559600604,
        "avg_acceptance_length": 8.533333333333333,
        "exact_match": "true",
        "notes": "Zero-copy exactness check versus plain MLX 4-bit.",
    },
    {
        "backfill_id": "chat_030",
        "backfill_order": 30,
        "script_name": "chat_backfill",
        "record_type": "historical",
        "history_source": "chat_log",
        "experiment_tag": "chat_backfill",
        "backend": "mlx",
        "target_model": "mlx-community/Qwen3.5-4B-MLX-4bit",
        "draft_model": "z-lab/Qwen3.5-4B-DFlash",
        "prompt_file": "prompts/functional_equation.txt",
        "max_new_tokens": 128,
        "prompt_tps": 851.90,
        "generation_tps": 162.06,
        "end_to_end_tps": 140.91,
        "avg_acceptance_length": 8.53,
        "peak_memory_gb": 3.78,
        "acceptance_lengths": [1, 2, 13, 4, 6, 14, 4, 6, 13, 8, 13, 10, 12, 9, 13],
        "notes": "Zero-copy warm CLI 4-bit run.",
    },
    {
        "backfill_id": "chat_031",
        "backfill_order": 31,
        "script_name": "chat_backfill",
        "record_type": "historical",
        "history_source": "chat_log",
        "experiment_tag": "chat_backfill",
        "backend": "llama.cpp",
        "target_model": "unsloth/Qwen3.5-4B-GGUF:Q4_K_M",
        "prompt_file": "/tmp/qwen35_chatprompt.txt",
        "max_new_tokens": 128,
        "prompt_tps": 887.06,
        "generation_tps": 76.42,
        "notes": "Clean llama.cpp one-shot completion benchmark.",
    },
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Backfill historical benchmark rows from this chat into the CSV history.")
    parser.add_argument(
        "--history-file",
        type=Path,
        default=DEFAULT_HISTORY_PATH,
        help="CSV file that accumulates benchmark history.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    existing_ids: set[str] = set()
    if args.history_file.exists():
        with args.history_file.open(newline="") as handle:
            reader = csv.DictReader(handle)
            for row in reader:
                if row.get("backfill_id"):
                    existing_ids.add(row["backfill_id"])

    pending_rows = [row for row in BACKFILL_ROWS if row["backfill_id"] not in existing_ids]
    append_rows(args.history_file, pending_rows)
    print(f"Appended {len(pending_rows)} backfill row(s) to {args.history_file}")


if __name__ == "__main__":
    main()
